/**
 * Domain models for ASTAR Assignment Completion Assistant
 * Phase 1: Minimal but complete domain layer
 */

/**
 * Types of assignments ASTAR can help with
 */
export type AssignmentType =
  | "essay"
  | "coding_project"
  | "problem_set"
  | "research_paper"
  | "presentation"
  | "other";

/**
 * Base assignment information (from Canvas or manual input)
 */
export interface Assignment {
  id: string;
  title: string;
  rawDescription: string;
  courseName?: string;
  courseId?: string;
  dueDate?: string; // ISO string
  points?: number;
  source?: "canvas" | "manual" | "other";
}

/**
 * A required deliverable for the assignment
 */
export interface AssignmentDeliverable {
  label: string;
  required: boolean;
}

/**
 * Structured analysis of an assignment
 * Generated by the assignment analysis service
 */
export interface AssignmentAnalysis {
  assignmentId: string;
  type: AssignmentType;
  requiredSkills: string[]; // e.g. ["python", "data visualization", "research"]
  estimatedTimeHours: number; // rough estimate
  prerequisites: string[]; // concepts, lectures, or topics student should know
  deliverables: AssignmentDeliverable[];
  successCriteria: string[]; // rubric-like checklist items
}

/**
 * A single step in the assignment completion journey
 */
export interface JourneyStep {
  id: string;
  title: string;
  description: string;
  estimatedMinutes: number;
  status: "not_started" | "in_progress" | "completed";
  resources?: string[]; // Optional learning resources for this step
}

/**
 * Complete journey for completing an assignment
 * Generated from the assignment analysis
 */
export interface AssignmentJourney {
  assignmentId: string;
  totalEstimatedMinutes: number;
  steps: JourneyStep[];
}

/**
 * Complete package returned by /api/assignments/analyze
 */
export interface AssignmentAnalysisResult {
  assignment: Assignment;
  analysis: AssignmentAnalysis;
  journey: AssignmentJourney;
}

