/**
 * Domain models for ASTAR Assignment Completion Assistant
 * Phase 1: Minimal but complete domain layer
 */

/**
 * Types of assignments ASTAR can help with
 */
export type AssignmentType =
  | "essay"
  | "coding_project"
  | "problem_set"
  | "research_paper"
  | "presentation"
  | "other";

/**
 * Base assignment information (from Canvas or manual input)
 */
export interface Assignment {
  id: string;
  title: string;
  rawDescription: string;
  courseName?: string;
  courseId?: string;
  courseCode?: string;
  dueDate?: string; // ISO string
  points?: number;
  source?: "canvas" | "manual" | "other";
}

/**
 * Canvas course context
 * Phase 2: Canvas-aware journey generation
 */
export interface CanvasContext {
  courseName: string;
  courseCode?: string | null;
  moduleTitles: string[];
  keyPages: Array<{ title: string; url: string }>;
  syllabusSnippet?: string | null;
}

/**
 * A required deliverable for the assignment
 */
export interface AssignmentDeliverable {
  label: string;
  required: boolean;
}

/**
 * Structured analysis of an assignment
 * Generated by the assignment analysis service
 */
export interface AssignmentAnalysis {
  assignmentId: string;
  type: AssignmentType;
  requiredSkills: string[]; // e.g. ["python", "data visualization", "research"]
  estimatedTimeHours: number; // rough estimate
  prerequisites: string[]; // concepts, lectures, or topics student should know
  deliverables: AssignmentDeliverable[];
  successCriteria: string[]; // rubric-like checklist items
}

/**
 * An MCP action that can be triggered for a step
 * Phase 2: MCP auto-suggestions
 */
export interface StepAction {
  id: string;
  label: string;
  kind: 'mcp';
  mcpType: string;
  mcpTool: string;
  payloadPreview?: any;
}

/**
 * A single step in the assignment completion journey
 */
/**
 * A resource link with usage guidance
 */
export interface Resource {
  title: string;
  url: string;
  type: string;
  howToUse?: string; // How to use this resource effectively
  preview?: string; // Short description/preview
}

export interface JourneyStep {
  id: string;
  title: string;
  description: string;
  estimatedMinutes: number;
  status: "not_started" | "in_progress" | "completed";
  resources?: Array<string | Resource>; // Optional learning resources
  actions?: StepAction[]; // Optional MCP action suggestions (Phase 2)
}

/**
 * Complete journey for completing an assignment
 * Generated from the assignment analysis
 */
export interface AssignmentJourney {
  assignmentId: string;
  totalEstimatedMinutes: number;
  steps: JourneyStep[];
}

/**
 * Complete package returned by /api/assignments/analyze
 */
export interface AssignmentAnalysisResult {
  assignment: Assignment;
  analysis: AssignmentAnalysis;
  journey: AssignmentJourney;
}

